void onlineUpdater();
void wlanStatus();
void wlanStatus1();
void loadConfig();
void saveConfig();
void changer(int set);
int getCpuClock();
int getBusClock();
void pspGetCpuBus();
void pspGetModel(int x, int y);
void aboutMenu();
void easterEgg();
void updatesMenu();
void performanceMenu();
void wait_release(unsigned int buttons);
unsigned int wait_press(unsigned int buttons);
void set_cpu_clock(int n);
void processorMenu();
void ramMenu();
void displayMenu();
void wifiMenu();
void developerMenu();
void settingsHighlight();
void settingsDeleteResources();
void settingsMenu();

